// Generated by Scapix Language Bridge
// https://www.scapix.com

#import "scapix/bridge/objc/BridgeObject.h"

NS_ASSUME_NONNULL_BEGIN

@interface WSNetRequestError : BridgeObject

-(BOOL)isSuccess;
-(BOOL)isDnsError;
-(BOOL)isCurlError;
-(NSString*)toString;
-(BOOL)isNoNetworkError;

@end

NS_ASSUME_NONNULL_END
