// Generated by Scapix Language Bridge
// https://www.scapix.com

#import "scapix/bridge/objc/BridgeObject.h"

NS_ASSUME_NONNULL_BEGIN

@interface WSNetHttpRequest : BridgeObject

-(NSString*)url;
-(uint32_t)timeoutMs;
-(NSString*)postData;
-(int)method;
-(NSString*)hostname;
-(uint16_t)port;
-(void)setUseDnsCache:(BOOL)isUseDnsCache;
-(BOOL)isUseDnsCache;
-(void)setContentTypeHeader:(NSString*)header;
-(NSString*)contentTypeHeader;
-(void)setIgnoreSslErrors:(BOOL)isIgnore;
-(BOOL)isIgnoreSslErrors;
-(void)setRemoveFromWhitelistIpsAfterFinish:(BOOL)isRemove;
-(BOOL)isRemoveFromWhitelistIpsAfterFinish;
-(void)setEchConfig:(NSString*)echConfig;
-(NSString*)echConfig;
-(void)setSniDomain:(NSString*)sniDomain;
-(NSString*)sniDomain;
-(NSString*)sniUrl;
-(void)setExtraTLSPadding:(BOOL)isExtraTLSPadding;
-(BOOL)isExtraTLSPadding;
-(void)setOverrideIp:(NSString*)ip;
-(NSString*)overrideIp;
-(void)setIsWhiteListIps:(BOOL)isWhiteListIps;
-(BOOL)isWhiteListIps;

@end

NS_ASSUME_NONNULL_END
