// Generated by Scapix Language Bridge
// https://www.scapix.com

#import "scapix/bridge/objc/BridgeObject.h"

NS_ASSUME_NONNULL_BEGIN

@interface WSNetDecoyTraffic : BridgeObject

-(void)setFakeTrafficVolume:(uint32_t)volume;
-(void)start;
-(void)stop;

@end

NS_ASSUME_NONNULL_END
