//
//  WindscribeTests-WindscribeMocks.generated.swift
//  Windscribe
//
//  Generated by Mockingbird v0.20.0.
//  DO NOT EDIT
//

#if canImport(SafariServices)
    import SafariServices
#endif
#if canImport(WidgetKit)
    import RxSwift
#endif
#if canImport(WidgetKit)
    import WidgetKit
#endif
import AppIntents
import AudioToolbox
import AVKit
import CocoaLumberjack
import CommonCrypto
import CoreData
import CoreLocation
import CoreMotion
import ExpyTableView
import Foundation
import ImageIO
import Intents
import IntentsUI
import IQKeyboardManagerSwift
import MobileCoreServices
@testable import Mockingbird
import Network
import NetworkExtension
import os.log
import Realm
import RealmSwift
import RxCocoa
import RxDataSources
import RxGesture
import RxRealm
import RxSwift
import SafariServices
import Security
import SimpleKeychain
import StoreKit
import Swift
import SwiftUI
@preconcurrency import Swinject
import SwipeCellKit
import SystemConfiguration.CaptiveNetwork
import UIKit
import WidgetKit
@testable import Windscribe
import WireGuardKit

// No mocks used in 'WindscribeTests'. Mockingbird is configured to only generate mocks for types
// that are explicitly initialized in your tests with `mock(SomeType.self)`. For more information,
// see 'Thunk Pruning' in the README.
