//
//  WindscribeTests-WindscribeMocks.generated.swift
//  Windscribe
//
//  Generated by Mockingbird v0.20.0.
//  DO NOT EDIT
//

#if canImport(SafariServices)
import SafariServices
#endif
#if canImport(WidgetKit)
import RxSwift
#endif
#if canImport(WidgetKit)
import WidgetKit
#endif
@preconcurrency import Swinject
@testable import Mockingbird
@testable import Windscribe
import AppIntents
import AudioToolbox
import BackgroundTasks
import CocoaLumberjack
import CocoaLumberjackSwift
import Combine
import CommonCrypto
import CoreData
import CoreLocation
import CoreMotion
import ExpyTableView
import Foundation
import IQKeyboardManagerSwift
import ImageIO
import Intents
import IntentsUI
import MobileCoreServices
import Network
import NetworkExtension
import Realm
import RealmSwift
import RxCocoa
import RxDataSources
import RxGesture
import RxSwift
import SafariServices
import Security
import SimpleKeychain
import SnapKit
import StoreKit
import Swift
import SwiftSoup
import SwiftUI
import Swinject
import SwipeCellKit
import SystemConfiguration.CaptiveNetwork
import UIKit
import UIKit.UIGeometry
import UniformTypeIdentifiers
import WidgetKit
import WireGuardKit
import os.log

// No mocks used in 'WindscribeTests'. Mockingbird is configured to only generate mocks for types
// that are explicitly initialized in your tests with `mock(SomeType.self)`. For more information,
// see 'Thunk Pruning' in the README.
