//
//  WindscribeTests-WindscribeMocks.generated.swift
//  Windscribe
//
//  Generated by Mockingbird v0.20.0.
//  DO NOT EDIT
//

@testable import Mockingbird
@testable import Windscribe
import AVKit
import AudioToolbox
import CocoaLumberjack
import CommonCrypto
import CoreData
import CoreLocation
import CoreMotion
import CoreTelephony
import ExpyTableView
import Foundation
import IQKeyboardManagerSwift
import ImageIO
import Intents
import IntentsUI
import JNKeychain
import MobileCoreServices
import Network
import NetworkExtension
import Realm
import RealmSwift
import RxCocoa
import RxDataSources
import RxGesture
import RxRealm
import RxSwift
import SafariServices
import Security
import StoreKit
import Swift
import Swinject
import SwipeCellKit
import SystemConfiguration.CaptiveNetwork
import UIKit
import WidgetKit
import WireGuardKit
import os.log

// No mocks used in 'WindscribeTests'. Mockingbird is configured to only generate mocks for types
// that are explicitly initialized in your tests with `mock(SomeType.self)`. For more information,
// see 'Thunk Pruning' in the README.
