// Generated by Scapix Language Bridge
// https://www.scapix.com

#import "scapix/bridge/objc/BridgeObject.h"

NS_ASSUME_NONNULL_BEGIN

@class WSNetEmergencyConnectEndpoint;
@class WSNetCancelableCallback;

@interface WSNetEmergencyConnect : BridgeObject

-(NSString*)ovpnConfig;
-(NSString*)username;
-(NSString*)password;
-(WSNetCancelableCallback*)getIpEndpoints:(void(^)(NSArray<WSNetEmergencyConnectEndpoint*>*))callback;

@end

NS_ASSUME_NONNULL_END
