// Generated by Scapix Language Bridge
// https://www.scapix.com

#import "scapix/bridge/objc/BridgeObject.h"

NS_ASSUME_NONNULL_BEGIN

@interface WSNetAdvancedParameters : BridgeObject

-(void)setAPIExtraTLSPadding:(BOOL)isEnabled;
-(BOOL)isAPIExtraTLSPadding;
-(void)setIgnoreCountryOverride:(BOOL)isIgnore;
-(BOOL)isIgnoreCountryOverride;
-(void)setCountryOverrideValue:(NSString*)country;
-(NSString*)countryOverrideValue;
-(void)setLogApiResponce:(BOOL)isEnabled;
-(BOOL)isLogApiResponce;

@end

NS_ASSUME_NONNULL_END
