// Generated by Scapix Language Bridge
// https://www.scapix.com

#import "scapix/bridge/objc/BridgeObject.h"

NS_ASSUME_NONNULL_BEGIN

@class WSNetDnsRequestResult;
@class WSNetCancelableCallback;
@class WSNetDnsResolver;
@class WSNetHttpRequest;
@class WSNetHttpNetworkManager;
@class WSNetServerAPI;
@class WSNetEmergencyConnectEndpoint;
@class WSNetEmergencyConnect;
@class WSNetPingManager;
@class WSNetAdvancedParameters;
@class WSNetUtils;

@interface WSNet : BridgeObject

+(void)setLogger:(void(^)(NSString*))loggerFunction debugLog:(BOOL)debugLog;
+(BOOL)initialize:(NSString*)platformName appVersion:(NSString*)appVersion isUseStagingDomains:(BOOL)isUseStagingDomains serverApiSettings:(NSString*)serverApiSettings;
+(WSNet*)instance;
+(void)cleanup;
-(void)setConnectivityState:(BOOL)isOnline;
-(void)setIsConnectedToVpnState:(BOOL)isConnected;
-(WSNetDnsResolver*)dnsResolver;
-(WSNetHttpNetworkManager*)httpNetworkManager;
-(WSNetServerAPI*)serverAPI;
-(WSNetEmergencyConnect*)emergencyConnect;
-(WSNetPingManager*)pingManager;
-(WSNetAdvancedParameters*)advancedParameters;
-(WSNetUtils*)utils;

@end

NS_ASSUME_NONNULL_END
