// Generated by Scapix Language Bridge
// https://www.scapix.com

#import "scapix/bridge/objc/BridgeObject.h"

NS_ASSUME_NONNULL_BEGIN

@class WSNetDnsRequestResult;
@class WSNetCancelableCallback;

@interface WSNetDnsResolver : BridgeObject

-(void)setDnsServers:(NSArray<NSString*>*)dnsServers;
-(WSNetCancelableCallback*)lookup:(NSString*)hostname requestId:(uint64_t)requestId callback:(void(^)(unsigned long long, NSString*, WSNetDnsRequestResult*))callback;
-(WSNetDnsRequestResult*)lookupBlocked:(NSString*)hostname;

@end

NS_ASSUME_NONNULL_END
