// Generated by Scapix Language Bridge
// https://www.scapix.com

#import "scapix/bridge/objc/BridgeObject.h"

NS_ASSUME_NONNULL_BEGIN

@interface WSNetEmergencyConnectEndpoint : BridgeObject

-(NSString*)ip;
-(uint16_t)port;
-(int)protocol;

@end

NS_ASSUME_NONNULL_END
