// Generated by Scapix Language Bridge
// https://www.scapix.com

#import "scapix/bridge/objc/BridgeObject.h"

NS_ASSUME_NONNULL_BEGIN

@interface WSNetCancelableCallback : BridgeObject

-(void)cancel;

@end

NS_ASSUME_NONNULL_END
