// Generated by Scapix Language Bridge
// https://www.scapix.com

#import "scapix/bridge/objc/BridgeObject.h"

NS_ASSUME_NONNULL_BEGIN

@interface WSNetDnsRequestResult : BridgeObject

-(NSArray<NSString*>*)ips;
-(uint32_t)elapsedMs;
-(BOOL)isError;
-(NSString*)errorString;

@end

NS_ASSUME_NONNULL_END
