// Generated by Scapix Language Bridge
// https://www.scapix.com

#import "scapix/bridge/objc/BridgeObject.h"

NS_ASSUME_NONNULL_BEGIN

@class WSNetCancelableCallback;
@class WSNetServerAPI;

@interface WSNetUtils : BridgeObject

-(int32_t)failoverCount;
-(NSString*)failoverName:(int)failoverInd;
-(WSNetCancelableCallback*)myIPViaFailover:(int)failoverInd callback:(void(^)(int, NSString*))callback;

@end

NS_ASSUME_NONNULL_END
