// Generated by Scapix Language Bridge
// https://www.scapix.com

#import "scapix/bridge/objc/BridgeObject.h"

NS_ASSUME_NONNULL_BEGIN

@class WSNetRequestError;

@interface WSNetDnsRequestResult : BridgeObject

-(NSArray<NSString*>*)ips;
-(uint32_t)elapsedMs;
-(WSNetRequestError*)error;

@end

NS_ASSUME_NONNULL_END
