// Generated by Scapix Language Bridge
// https://www.scapix.com

#import "scapix/bridge/objc/BridgeObject.h"

NS_ASSUME_NONNULL_BEGIN

@class WSNetCancelableCallback;
@class WSNetServerAPI;

@interface WSNetBridgeAPI : BridgeObject

-(void)setConnectedState:(BOOL)isConnected;
-(void)setIgnoreSslErrors:(BOOL)bIgnore;
-(BOOL)hasSessionToken;
-(void)setApiAvailableCallback:(void(^)(BOOL))callback;
-(void)setCurrentHost:(NSString*)host;
-(WSNetCancelableCallback*)rotateIp:(void(^)(int, NSString*))callback;
-(WSNetCancelableCallback*)pinIp:(NSString*)ip callback:(void(^)(int, NSString*))callback;

@end

NS_ASSUME_NONNULL_END
