
// Objective-C API for talking to the following Go packages
//
//	wstunnel/proxy
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Proxy_FRAMEWORK_H__
#define __Proxy_FRAMEWORK_H__

#include "Proxy.objc.h"
#include "Universe.objc.h"

#endif
